# Generated by Django 2.2.4 on 2019-08-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
