# Generated by Django 2.2.4 on 2019-08-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0003_auto_20190817_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
