# Generated by Django 2.2.4 on 2019-08-18 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0006_breakdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakdown',
            name='machine',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='breakdowns.Machine'),
        ),
    ]
