# Generated by Django 2.2.4 on 2019-08-19 20:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0007_breakdown_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakdown',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
