# Generated by Django 2.2.4 on 2019-08-22 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0008_breakdown_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdown',
            name='start_time',
            field=models.DateTimeField(default='2006-10-25 14:30'),
        ),
    ]
