# Generated by Django 2.2.4 on 2019-08-22 20:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0011_auto_20190822_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdown',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
