# Generated by Django 2.2.4 on 2019-08-22 21:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0012_auto_20190822_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdown',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 22, 21, 0, 32, 595369, tzinfo=utc)),
        ),
    ]
